### PR TITLE
CoC: add committee members to CoC text

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Solving https://github.com/pydata/pandas-governance/commit/1376493cdbfaa22adebd72cf1891db415f9f6923#commitcomment-18587703

But, we also have to decide on how people can contact those members. So either adding the email addresses of the different people listed there, or making a generic email address that is forwarded to those people.

### CODE REVIEW

**Comment by wesm** [comment]
Guess we should create a private CoC list that can receive incoming e-mail. What's the best service for this, Google groups?

**Comment by wesm** [comment]
created pandas-doc@googlegroups.com 

I'm inviting the initial members. Can you add this e-mail address to the patch and say that anyone can e-mail the CoC and these messages are only visible to the CoC / not publicly?

**Comment by jorisvandenbossche** [comment]
Added the email address

**Comment by wesm** [comment]
Thank you. Merging!

**Pull request merged**
